### ISSUE TITLE
the request of pre-trained model

### ISSUE THREAD

**Issue by Do1e** [mandt-lab/shallow-ntc#1]
Hello.
Great research and I'm interested in it.
Will the pre-trained model be made public?

**Comment by yiboyang** [comment]
Hi, 
Thanks for your interest. I have added the checkpoints at https://huggingface.co/yiboyang/shallow-ntc-checkpoints/. Please see README for more details.

**Comment by Do1e** [comment]
It seems that there are some problems with the pre-trained model of two_layer_syn. The RD performance is extremely poor.
wid=0, bpp=1.4086381, psnr=23.93254
wid=1, bpp=0.7251964, psnr=25.71462

**Comment by yiboyang** [comment]
Turns out there was an issue with the config files for two_layer_syn (I used gelu activation instead of igdn by accident). Pull the huggingface repo and it should be fixed now. 

You should see
wid=0, rd_lambda=0.08, bpp=1.306146, psnr=38.787266
wid=1, rd_lambda=0.02, bpp=0.67281914, psnr=34.59338

**Comment by Do1e** [comment]
Thank you very much.
