### ISSUE TITLE
How to calculate the KMACs (thousand multiply-accumulate operations) per pixel?

### ISSUE THREAD

**Issue by zhoumenghan** [mandt-lab/shallow-ntc#2]
Hi, very happy to follow your great work! I want to know how to calculate the KMACs (thousand multiply-accumulate operations) per pixel. Divide the number of MACs by the number of pixels? (1920x1080x3 or 1920x1080)?

**Comment by yiboyang** [comment]
Hi, thanks for your interest. In your example, an RGB image tensor of shape 1920x1080x3 would have 1920x1080 pixels. So we'll count the number of FLOPs needed to decode such an image and divide by 1920x1080 to get the FLOPs/pixel; further dividing this by 2 x 1000 will give us the kMACs/pixel (1 MAC ≈ 2 FLOPs). See example calculations here: https://github.com/mandt-lab/shallow-ntc/blob/master/notebooks/get_flops.ipynb
